########################################
# Platform
########################################
platformName=Android
automationName=UiAutomator2

########################################
# Device
########################################
# Optional: set via -DdeviceName / DEVICE_NAME
deviceName=AndroidDevice

# Optional: leave empty for auto-detection
platformVersion=
udid=

########################################
# Application
########################################
# Can be overridden via -Dapp or APP
app=apps/app.apk
appPackage=com.tui.qa.challenge
# Optional: if blank, Appium launches default activity from manifest
# appActivity=.MainActivity
appActivity=.MainActivity

########################################
# Optional Test Inputs
########################################
# Used only if date is not passed from test data
dateOfBirth=01/06/1990

########################################
# Waits
########################################
implicitWait=10
explicitWait=20

########################################
# Appium Server
########################################
appiumServerURL=http://127.0.0.1:4723